### ISSUE TITLE
Add token to the HTTP header when froala makes HTTP request

### ISSUE THREAD

**Issue by nsatishnaidu** [froala/wysiwyg-editor-dotnet-sdk#1]
Our project has an Angular 2 client side interacting with a ASP.NET Web API on the server. 

When we are configuring an instance of the Froala editor to allow for image uploads, we have the following setting in our Angular 2 component:

`$(function () {
            $('div#ed' + divid).froalaEditor({
                heightMin: 100,
                toolbarInline: false,
                widthMin: 100,
                imageUploadURL: 'http://outili.com:8067/FroalaApi/UploadImage',
                toolbarButtons: ['bold', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|'
                    , 'align', 'undo', 'redo', 'selectAll', '|', 'insertImage'],
                toolbarButtonsXS: ['undo', 'redo', '-', 'bold', 'italic', 'underline'],
                //toolbarVisibleWithoutSelection: true,
                pluginsEnabled: null,
                charCounterCount: false
            })
        });`

As you can see, we are calling an absolute URL as opposed to a relative URL (as in the example). 
Now Froala editor makes the AJAX call to this URL to send the request and get the response (link to the image) and displays it in the editor. 

Is there a way in which we can modify the HTTP request header when Froala sends this request. The thing is that the API expects an authentication token, and because of the absence, we are unable to integrate. Does the editor accept a function as a property, which can then make the HTTP request on its behalf?

**Comment by nsatishnaidu** [comment]
This link explains it. Thank you so much:

https://wysiwyg-editor.froala.help/hc/en-us/articles/115000541089-Is-it-possible-to-set-an-authentication-header-

**Comment by yousafravian** [comment]
Can you please guide how to change token value in case token is expired without recreating a new froala instance
