### ISSUE TITLE
File upload throwing error but file is generated

### ISSUE THREAD

**Issue by codeandcloud** [froala/wysiwyg-editor-dotnet-sdk#10]
Trying to upload a file to server using the code,

    string uploadPath = "/Public/";
    object response = FroalaEditor.File.Upload(System.Web.HttpContext.Current, uploadPath);
which uploads a file to server as per [the documentation](https://www.froala.com/wysiwyg-editor/docs/sdks/dotnet/file-server-upload)

It fails with the error, 

> E:/path/to/file/file-name.docx' is a physical path, but a virtual path was expected.

But the file is being created on the server.  We also have 

    string uploadPath = "/Public/";
    object response = FroalaEditor.Image.Upload(System.Web.HttpContext.Current, uploadPath);
which works without any issue.

Importantly, **when we look inside the "Public" folder we see the file being created with content**.

Why is the Image upload working and File upload not working? Any pointers will be very helpful

**Comment by royal** [comment]
+1 Error is also occurring for me.

Looks like it has been fixed in this pull request - https://github.com/froala/wysiwyg-editor-dotnet-sdk/pull/3
