### ISSUE TITLE
Image uploads to s3 return escaped url

### ISSUE THREAD

**Issue by powermikee** [froala/wysiwyg-editor-dotnet-sdk#12]
When you upload images to s3 the url is coming back escaped for example:

KeyStart = 'uploads/test',

https://s3-ap-southeast-2.amazonaws.com/test-steelx-root/uploads%2Ftest%2Fimage.jpeg

Should obviously be: 
https://s3-ap-southeast-2.amazonaws.com/test-steelx-root/uploads/test/image.jpeg

**Comment by stefanneculai** [comment]
@powermikee do you think you could make a PR for it?

**Comment by stefanneculai** [comment]
This should be working fine on the latest version of editor and .NET SDK.
