### ISSUE TITLE
Parsing response failed when uploading image (.NET)

### ISSUE THREAD

**Issue by mapretel** [froala/wysiwyg-editor-dotnet-sdk#8]
Hello,

I'm having a problem when doing the response parser, in question FROALA gives me the error: "Parsing response failed.", although the object obtained is the following "{"link":"Upload/1695423b.png"} "

The image is correctly uploaded to the server, the path to which the test is referenced in the browser and the image looks correct, but still gives the error What is happening?

I have the latest version of Froala deployed and the browser used is IE11 version 11.0.9600.18893 and ChromeVersion 64.0.3282.186.

Attached screenshots and Word file with the source of both the upload and the file containing FROALA

Best regards !!

**Source Code:**
[CODE.docx](https://github.com/froala/wysiwyg-editor/files/1802409/CODE.docx)

![browser](https://user-images.githubusercontent.com/27733084/37279922-2d053496-25e4-11e8-8950-a66363f5af48.JPG)

![image](https://user-images.githubusercontent.com/27733084/37281048-96d0eaca-25e7-11e8-955a-a539de90e7ae.JPG)

##### OS.
Windows 7  + IIS7

##### Browser.
IE11 version 11.0.9600.18893 and ChromeVersion 64.0.3282.186.

**Comment by MrHantLP** [comment]
Hi. You have this error because in some reason it’s not a JSON object. You saw it in a console, it’s just a string, objects looks different. In my .NET Core project I am using this one 
`return Json(new {link = imageLink})`

I previously used JsonConverter.SerializedObject() and I faced with the same problem.

**Comment by mapretel** [comment]
I try to créate a new class:
       public class ImageLinkJson {
              [JsonProperty("link")]
              public string link { get; set; }
      }

And Invoke it from the load method of my page upload.aspx and return in the response the object : 

                        ImageLinkJson imageLinkJson = new ImageLinkJson();
                        imageLinkJson.link = urlPath;                               
                        HttpContext.Current.Response.StatusCode = 200;
                        HttpContext.Current.Response.ContentType = "application/json; charset=utf-8";
                        HttpContext.Current.Response.Write((object)JsonConvert.SerializeObject(imageLinkJson));
                        HttpContext.Current.Response.Flush(); 
                        HttpContext.Current.Response.SuppressContent = true;  
                        HttpContext.Current.ApplicationInstance.CompleteRequest();

**And the result is :** 
![screencapture 1](https://user-images.githubusercontent.com/27733084/37352482-42dfcbe0-26d5-11e8-8912-82d0cb8e78f3.JPG)
![screencapture_2](https://user-images.githubusercontent.com/27733084/37352485-430c4c06-26d5-11e8-8be7-4d92c888cb47.JPG)
![screencapture_3](https://user-images.githubusercontent.com/27733084/37352486-4334df90-26d5-11e8-8680-4376a8fabde5.JPG)
![screencapture_4](https://user-images.githubusercontent.com/27733084/37352488-4366af2a-26d5-11e8-937a-3df52120e760.JPG)

**Source code:**
[wwwroot.zip](https://github.com/froala/wysiwyg-editor-dotnet-sdk/files/1807617/wwwroot.zip)

**Comment by stefanneculai** [comment]
Looks like you are passing wrong options when initializing the editor. Please pass the following ones:
```js
 $('#edit').froalaEditor({
                  imageManagerLoadMethod: 'GET',
                  imageManagerLoadURL: "http://localhost/upload",
                  // Set the image upload URL.
                  imageUploadURL: '/Upload.aspx',
                  fileMaxSize: 1024 * 1024 * 150,
                  imageUploadParam: 'file',
                  imageAllowedTypes: ['jpeg', 'jpg', 'png']
              })
```
